### PR TITLE
stock: add batch to recompute StockLocationLine entries

### PR DESCRIPTION
**Pull request by beuss**
Preliminary work, add batch structure and logic for non-detail stock
locations. We'll have to move this into supplychain module to handle
reservedQuantity correctly.

ref #2071

### CODE REVIEW

**Comment by beuss** [comment]
Please @gdu-axelor or @pdo-axelor  take a look at this preliminary work as all business rules are extrapolated from source code. I guess I should move it to supplychain module as I can't access to ReservedQty otherwise.
By the way, could someone explain me what reservedQty is meant to be? The whole stock handling code is quite opaque (especially with its two parameters future & current where current is always passed as true from what I saw), how is the moveLine reservedQty value set?

**Comment by pdo-axelor** [comment]
Are you sure you need to use native queries? It might cause portability issues.
Also, there might be memory issues with big result lists. It's better to use limit and/or offset on queries.
Besides, batches should update done and anomaly counts.

**Comment by beuss** [comment]
I'll try to rewrite queries in HQL, native is the result of some tries I had previously, shouldn't be an issue.
The main point is to check that computations are correct before optimizing memory & report anomalies/done.

**Comment by beuss** [comment]
I removed the native queries & used a windowed system. Could you check that I use correct information for recalculation so I could finish it? (I'll add success/anomalies count at the end)

**Pull request closed without merging**
